apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      storage: {{ .Values.pvcRequestsStorage }}
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
